# permissions for end users to edit collectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector-editor-role
rules:
- apiGroups:
  - lab.apodemas
  resources:
  - collectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lab.apodemas
  resources:
  - collectors/status
  verbs:
  - get
